const Home = () => {
  return (
    <div className="dark:text-white">
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
      <h1>my Home Page</h1>
    </div>
  );
};

export default Home;
